#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get -y install haproxy

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 35253-web-01 3.239.2.1:80 check\n\tserver 35253-web-02 18.207.207.9:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
