#!/usr/bin/env bash
# A script to display "To infinity and beyond" indefinitely with
# sleep 2 in between each iteration.
# Displays "I am invincible!!!" in between each iteration
trap 'echo "I am invicible!!!"' SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
