#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times
# but for the 9th iteration, displays Best School and then Hi
#  on a new line.
i=1
while [ $i -lt 11 ];
do
	if [ $i -eq 10 ];
	then
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
