#!/usr/bin/env bash
# Script display 1 to 20 and make use of case statement
# at 4 then print 'bad luck from China'
# at 9 then print 'bad luck from Japan'
# at 17 then print 'bad luck from Italy'
i=1
while [ $i -lt 21 ];
do
	case $i in
		5)
			echo "bad luck from China"
		;;
		10)
			echo "bad luck from Japan"
		;;
		18)
			echo "bad luck from Italy"
		;;
	esac
	echo "$i"
	((i++))
done	
