#!/usr/bin/env bash
#  Bash script that gives you information about the school file.
# print if the file exists: school file exists
#+ if the file is empty: school file is empty
#+ if the file is not empty: school file is not empty
#+ if the file is a regular file: school is a regular file
#+ if the file is not a regular file: (nothing)
# print if the file does not exist: school file does not exist

